# Generated by Django 4.2.11 on 2024-03-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.TextField(blank=True, verbose_name='file_path'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.TextField(choices=[('movie', 'movie'), ('tv_show', 'tv show')], verbose_name='type'),
        ),
    ]
